### ISSUE TITLE
Problems with keyboards

### ISSUE THREAD

**Issue by mcstllns** [hosein2398/node-telegram-bot-api-tutorial#2]
I'm following your tutorial but I can't create keyboards, however I can see them in other bots (eg. TriviaBot). This is the code (copied from you tutorial), I have no idea what is wrong. When I send "/star" I only see "welcome".

const TelegramBot = require('node-telegram-bot-api'); 
const token = 'XXX:XXXXX';
const bot = new TelegramBot(token, {polling: true});
  
bot.onText(/\/start/, (msg) => {

	bot.sendMessage(msg.chat.id, "Welcome", {
	"reply_markup": {
	    "keyboard": [["Sample text", "Second sample"],   ["Keyboard"], ["I'm robot"]]
	    }
	});
});

Thank you so much for your help.

**Comment by hosein2398** [comment]
I've just tested and there is no problem,
your problem might be that your not using Regex well:
```
bot.onText(//start/, (msg) => {

bot.sendMessage(msg.chat.id, "Welcome", {
"reply_markup": {
    "keyboard": [["Sample text", "Second sample"],   ["Keyboard"], ["I'm robot"]]
    }
});
});
```
should be : 
```
bot.onText(/\/start/, (msg) => {

bot.sendMessage(msg.chat.id, "Welcome", {
"reply_markup": {
    "keyboard": [["Sample text", "Second sample"],   ["Keyboard"], ["I'm robot"]]
    }
});
});
```
Difference is in `bot.onText(/\/start/, (msg) => { . . . `

**Comment by mcstllns** [comment]
Thank you very much for your quick response.

That was a copying/pasting mistake, but in the code was right. The problem is already solved. I was using a Token created over a year ago, I've created a new one and now it works perfectly, maybe some change in Botfather's policies.

Thank you so much for your time and help, and I'm sorry I bothered you with such a stupid question.
